INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
BID_TID_COLUMN = 4
FIRST_COLUMN = 5
NUM_BYTES_PER = 8
PAGE_ARRAY_SIZE = 4096
PAGE_SETS_PER_TAIL = 4
PAGE_CAPACITY = int(PAGE_ARRAY_SIZE / NUM_BYTES_PER)
BITS_PER_BYTE = 8
BUFFER_POOL_SIZE = 10000
POOL_PATH_DEFAULT = "./mypool"
HOW_MANY_TO_EVICT = 50
MERGE_TRIGGER = 1280

DELETE_NODE = -1

BITS_USED_FOR_RID_INDEX = 9
BITS_USED_FOR_SETID = NUM_BYTES_PER * BITS_PER_BYTE - BITS_USED_FOR_RID_INDEX
BITS_USED_FOR_RID_MASK = 2 ** BITS_USED_FOR_RID_INDEX - 1

BITS_USED_FOR_COLUMN_ID = 6
BITS_USED_FOR_COLUMN_ID_MASK = 2 ** BITS_USED_FOR_COLUMN_ID - 1

MAX_64_BITS = 18446744073709551615
CONFIG_PATH = "config/"
INDEX_PATH = "index/"


def rid_decoder(rid: int):
	return rid >> BITS_USED_FOR_RID_INDEX, rid & BITS_USED_FOR_RID_MASK


def rid_encoder(pageset_id, at_index):
	return pageset_id << BITS_USED_FOR_RID_INDEX | at_index


